<!DOCTYPE html>
<html>
<head>
	<title>Bioseminal</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

<style>
	.columnright{
		width:25%;

	}
	.columnleft{
		width:75%;
		padding:20px; 
	}
</style>
</head>
<body>
	<div style="margin:10px 0px 0px 60px; padding-top: 40px; background-color: red; "><h1>BioSentinel</h1></div>
<section style="margin: 60px;">
<div class="row" style="padding-bottom:10px; ">
	<div class="columnleft" >
<p>The BioSentinel mission was selected in 2013 as one of the secondary payloads to fly on the Space Launch System's first Exploration Mission (EM-1) planned for launch in July 2018. &nbsp;The primary objective of BioSentinel is to develop a biosensor using a simple model organism to detect, measure, and correlate the impact of space radiation to living organisms over long durations beyond Low Earth Orbit (LEO). &nbsp;While progress identifying and characterizing biological radiation effects using Earth-based facilities has been significant, no terrestrial source duplicates the unique space radiation environment.</p>

<p>The BioSentinel biosensor uses the budding yeast&nbsp;<em>S. cerevisiae</em>&nbsp;to detect and measure double strand breaks (DSBs) that occur in response to ambient space radiation. &nbsp;DSBs are deleterious DNS lesions that are generated by exposure to highly energetic particles in the deep-space radiation without errors by the cell. &nbsp;The biosensor consists of genetically engineered yeast strains and nutrient selection strategies that ensure that only cells that have repaired DSBs will grow in specialized media. &nbsp;Therefore, culture growth and metabolic activity of yeast cells directly indicate a successful DSB-and-repair event.</p>



<p>In the BioSentinel payload, yeast cells are stored dried in microfluidic cards inside a 6-Unit (6U) spacecraft measuring approximately 14.4 inches long, 9.4&nbsp;inches wide, and 4.6&nbsp;inches tall. &nbsp;It weighs about 30 pounds. &nbsp;At launch, BioSentinel resides within the second stage on the launch vehicle from which it is deployed to a lunar fly-by trajectory and into a heliocentric orbit where its distance to the sun is slightly closer than Earth's, varying between 0.98 to 0.92 times Earth's distance to the sun. &nbsp;After completing the lunar fly-by and spacecraft checkout, the science mission phase begins with the wetting of the first set of cell-containing wells with specialized media. &nbsp;The microfluidic cards carry three yeast strains: wild type (similar to yeast strains found in nature),&nbsp;<em>rad51</em>&nbsp;mutant (defective in DSB repair), and the DSB biosensor strain. &nbsp;Each set of wells is expected to be in its active mode for 2-4 weeks following hydration; multiple sets of wells will be activated at different time points over the 18-month mission. &nbsp;One reserve set of wells will be activated in the occurrence of a Solar Particle Event (SPE). &nbsp;Payload science data and spacecraft telemetry will be stored on board and then downloaded to the&nbsp;ground.</p>

<p>Growth and metabolic activity of the yeast cells will be measured using a 3-color LED detection system and the metabolic indicator dye alamarBlue. &nbsp;Biological measurements will be compared to data provided by onboard physical sensors an dosimeters to obtain total ionizing radiation dose and particle characterization, and to Earth-based experiments using relevant energetic particle types, energies, and doses. &nbsp;Additionally, three identical BioSentinel payloads will be developed - one for the International Space Station (ISS), where there is similar microgravity but a comparatively low-radiation environment, one for use as a delayed-synchronous ground control at Earth gravity and also with a low radiation environment, and one ground payload that will be used at Brookhaven National Laboratory in New York for radiation testing. &nbsp;Thus the BioSentinel payload will help calibrate the biological effects of radiation in deep space to analogous measurements conducted on Earth and on the ISS.</p>

<p>​BioSentinel will conduct the first study of biological response to space radiation outside LEO in over 40 years. &nbsp;BioSentinel will address strategic knowledge gaps related to the biological effects of space radiation and will provide an adaptable platform to perform human-relevant measurements in multiple space environments in the future. &nbsp;Yeast is the ideal organism for this mission because of its spaceflight heritage, it is highly capable of repairing DSBs, and it can be stored in stasis for a long period of time. &nbsp;Moreover, the DSB repair mechanisms in yeast are well studied and highly similar to those in human cells. &nbsp;BioSentinel's&nbsp;results will be critical for improving interpretation of the effects of space radiation exposure, and for reducing the risk associated with long-term human exploration.</p>

<p>The BioSentinel mission is funded by the Advanced Exploration Systems program within the Human Exploration and Operations Mission Directorate at NASA Headquarters. &nbsp;Partner organizations include NASA Ames Research Center, NASA Johnson Space Center, Loma Linda University Medical Center, and the University of&nbsp;Saskatchewan, Canada.</p>
</div>

	<div class="columnright"> 
<img typeof="foaf:Image" src="images/Bioseminal.jpg" width="320" height="242" alt="BioSentinel Fluidics Card" >
BioSentinel’s microfluidics card, designed at NASA Ames, will be used to study the impact of interplanetary space radiation on yeast. Once in orbit, the growth and metabolic activity of the yeast will be measured using a 3-color LED detection system and a metabolic indicator dye. Here, pink wells contain actively growing yeast cells that have turned the metabolic dye from blue to pink color.<br>
<br>
<img typeof="foaf:Image" src="images/dna.jpg" width="320" height="302" alt="Conceptual graphic of a radiation particle causing a DNA DSB" title="">
<div>Conceptual graphic of a radiation particle causing a DNA DSB</div>
</div>
</div>
</section>
</body>
</html>