<!DOCTYPE html>
<html>
<head>
	<title>Ea.coli</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

	<style>

	h1{
		background-color:red;
		text-align: center;

	}
</style>
<div>
<h1>NASA Affordable Vehicle Avionics (AVA)</h1>
</div>
</head>
<body>
<div style="margin:0px 20px 0px 20px;"> 
<img class="listicle-product-slide-image listicle-slide-media listicle-slide-media-product lazyimage lazyloaded" src="images/ea.png" height="500px" width="500px">

<section >   
<div>
<h2>Investigating Space&nbsp;Microgravity&nbsp;Effects on Antibiotic Resistance of&nbsp;<em>E. coli</em></h2>

<p>The <i>E. coli</i> AntiMicrobial Satellite (EcAMSat) mission will investigate space microgravity effects on the antibiotic resistance of <i>E.</i> <i>coli</i>, a bacterial pathogen responsible for urinary tract infection in humans and animals. EcAMSat is being developed through a partnership between NASA’s Ames Research Center and the Stanford University School of Medicine. Dr. A.C. Matin is the Stanford University Principal Investigator. EcAMSAT is slated for launch in November 2017.</p>

<p>EcAMSat will investigate spaceflight effects on bacterial antibiotic resistance and its genetic basis. Bacterial antibiotic resistance may pose a danger to astronauts in microgravity, where the immune response is weakened. Scientists believe that the results of this experiment could help design effective countermeasures to protect astronauts’ health during long-duration human space missions.</p>

<p>The fundamental scenario of the experiment protocol starts four&nbsp;days after launch of the EcAMSat satellite by allowing an initial growth and then starvation period for <i>E. coli</i> bacteria contained in 48 microfluidic wells. Both wild type (occurring in nature) and mutant strains of <i>E. coli</i> are used. This cycle lasts 48&nbsp;hours and serves to prepare the bacteria for introduction of the antibiotic agent at a time most suitable for meaningful comparisons of antibiotic dose dependence with laboratory data. After this 48-hour growth period, a buffer solution- plus-antibiotic mixture is dispensed into 3 sets of 12-well banks at three different antibiotic concentrations and is left to incubate for 48&nbsp;hours. A fourth 12-well set is a control and receives no antibiotic agent, only buffer solution. After 48&nbsp;hours a fluid exchange occurs and alamarBlue<sup>®</sup>, a dye used to determine viability of the bacteria by measuring its metabolism, is then introduced to all wells and viability is tracked for at least 48&nbsp;hours. An optical system tracks viability by color change of the ‘viability dye’, which changes from blue to pink when enzymes generated by cellular metabolic processes act upon it. EcAMSat acquires data from optical measurements in real-time. It is capable of autonomous operation and stores 152&nbsp;hours of data. Overall, the experiment will determine the lowest concentration of antibiotic that inhibits bacterial growth. The knowledge gained in this experiment may be useful for prescribing the correct dose of antibiotics for future space travelers.</p>

<p>EcAMSat will utilize flight proven spacecraft technologies demonstrated on prior Ames nanosatellite missions such as PharmaSat and Organism/Organic Exposure to Orbital Stresses (O/OREOS). Several other 6U spacecraft that have launched use the dimensions defined by the EcAMSat Team at NASA Ames.These dimensions now define the 6U Standard. In the 6U configuration, EcAMSat has six times the volume of a single CubeSat unit (1U). The cube-shaped 1U satellites measure about 4 inches on each side, have an approximate volume of one quart, and weigh less than three pounds. The 6U format enhances nanosatellite applicability for space missions by providing more power and volume for instruments, avionics, actuators and propulsion. The larger format improves payload accommodation and extends mission duration capabilities, while still retaining its ability to be launched as a secondary payload. EcAMSat weighs about 23 pounds and measures approximately 14.4 inches long, 8.9 inches wide and 3.9 inches tall. In addition, EcAMSat will serve to demonstrate the 6U satellite platform with two separate payload volumes.</p>

<p>The mission is funded as part of the Space Biology Project at NASA Ames Research Center. Funding for Space Biology comes from the Space Life and Physical Sciences Research and Applications Division within the Human Exploration and Operations Mission Directorate at NASA Headquarters.</p>
</section>  </div>
</body>
</html>